FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY . .
RUN ./mvnw test
CMD ["java", "-jar", "target/backend-0.0.1-SNAPSHOT.jar"]

#FROM eclipse-temurin:17-jdk AS build
#WORKDIR /app
#COPY . .
#
#RUN chmod +x mvnw
#
#RUN ./mvnw -q package
#
#FROM eclipse-temurin:17-jre
#WORKDIR /app
#
#COPY --from=build /app/target/backend-0.0.1-SNAPSHOT.jar app.jar
#EXPOSE 8080
#ENTRYPOINT ["java","-jar","app.jar"]